config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :kids do
    patch :moana_avatar, on: :member
    patch :pocahontas_avatar, on: :member
    patch :mogli_avatar, on: :member
    patch :tarzan_avatar, on: :member
    patch :simba_avatar, on: :member
    patch :ariel_avatar, on: :member
    patch :capitao_avatar, on: :member
    patch :frozen_avatar, on: :member
    resources :games, only: [:index, :show] do
      patch :completed, on: :member
      member do
        get :lecture
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  has_many :kids
  has_one_attached :photo
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :kid

  has_many_attached :photos
  has_many_attached :videos
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :user
  belongs_to :avatar
  has_many :games, dependent: :destroy

  validates :nickname, :age, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :kids, dependent: :destroy

  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show lecture completed]
  before_action :set_kid, only: %i[lecture completed index show]
  protect_from_forgery with: :null_session

  def index
    @games = @kid.games
  end

  def show
  end

  def lecture
  end

  def completed
    @game.update(completed: true)
    @kid.update(total_score: @kid.total_score + 1)

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def set_kid
    @kid = Kid.find(params[:kid_id])
  end

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kids, only: %i[show destroy edit moana_avatar pocahontas_avatar mogli_avatar tarzan_avatar simba_avatar ariel_avatar capitao_avatar frozen_avatar]
  protect_from_forgery with: :null_session

  def index
    @kids = current_user.kids
  end

  def show
  end

  def new
    @kid = Kid.new
  end

  def create
    @kid = Kid.new(kid_params)
    # Give a parent for the kid
    @kid.user = current_user
    # Give an avatar for the kid
    @kid.avatar = Avatar.last
    if @kid.save
      CreateGames.call(kid: @kid)
      # redirect to choose the avatar
      redirect_to edit_kid_path(@kid)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @moana = Avatar.find_by(name: "moana")
    @pocahontas = Avatar.find_by(name: "pocahontas")
    @mogli = Avatar.find_by(name: "mogli")
    @tarzan = Avatar.find_by(name: "tarzan")
    @simba = Avatar.find_by(name: "simba")
    @ariel = Avatar.find_by(name: "ariel")
    @capitao = Avatar.find_by(name: "capitao")
    @frozen = Avatar.find_by(name: "frozen")
  end

  def moana_avatar
    avatar = Avatar.find_by(name: "moana")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def pocahontas_avatar
    avatar = Avatar.find_by(name: "pocahontas")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def mogli_avatar
    avatar = Avatar.find_by(name: "mogli")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def tarzan_avatar
    avatar = Avatar.find_by(name: "tarzan")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def simba_avatar
    avatar = Avatar.find_by(name: "simba")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def ariel_avatar
    avatar = Avatar.find_by(name: "ariel")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def capitao_avatar
    avatar = Avatar.find_by(name: "capitao")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def frozen_avatar
    avatar = Avatar.find_by(name: "frozen")
    @kid.avatar = avatar
    @kid.save

    respond_to do |format|
      format.json { head :ok }
      format.html { head :ok }
    end
  end

  def update
    @kid.update(kid_params)
    redirect_to kid_path(@kid)
  end

  def destroy
    @kid.destroy
    redirect_to kids_path
  end

  private

  def kid_params
    params.require(:kid).permit(:nickname, :age)
  end

  def set_kids
    @kid = Kid.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/games/index.html.erb
<%= render "shared/map-navbar", kid: @kid %>

<div class="map">
  <div class="games container text-center py-5">
  <%= image_tag "boat.png", id: "boat", alt: "boat", width: 90 %>

    <% @games.each do |game| %>

      <% if @kid.total_score + 1 > game.level %>
        <%= image_tag "treasure-open.png", alt: "chest-open", width: 60, class:"played", id: "game#{game.name}" %>
      <% elsif @kid.total_score + 1 == game.level %>
        <%= link_to lecture_kid_game_path(@kid, game), id: "game#{game.name}" do %>
          <%= image_tag "treasure-open.png", alt: "chest-open", width: 60, id: "current-game" %>
        <% end %>
      <% else %>
        <%= image_tag "treasure-closed-bw.png", alt: "chest-closed", id: "game#{game.name}", class:"blocked-game", width: 60 %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/games/lecture.html.erb
<%= render "shared/sidebar", kid: @kid %>

  <div class="container">

    <div class="d-flex justify-content-center mt-4">

      <% if @kid.total_score == 0 %>
        <%= cl_video_tag @game.videos[0].key, :controls => true, width:"350px", class:"card-lecture shadow" %>
      <% elsif @kid.total_score == 1 %>
        <%= cl_video_tag @game.videos[0].key, :controls => true, width:"350px", class:"card-lecture shadow" %>
      <% elsif @kid.total_score == 2 %>
        <%= cl_video_tag @game.videos[0].key, :controls => true, width:"350px", class:"card-lecture shadow" %>
      <% elsif @kid.total_score == 3 %>
        <%= cl_video_tag @game.videos[0].key, :controls => true, width:"350px", class:"card-lecture shadow" %>
      <% end %>

    </div>

    <div class="mt-5 d-flex justify-content-center">
      <%= link_to "Let's play!", kid_game_path(@kid, @game), class:"btn-brown" %>
    </div>
  </div>

app/views/games/show.html.erb
<%= render "shared/sidebar", kid: @kid %>

<%# Condition for the voice %>
<% female = @kid.avatar.name == "moana" || @kid.avatar.name == "pocahontas" || @kid.avatar.name == "ariel" || @kid.avatar.name == "frozen" %>

<div data-controller="game">
  <%# Taking the targets for the game controller  %>
  <div class="d-none" data-game-target="gameId">
    <%= @game.id %>
  </div>
  <div class="d-none" data-game-target="kidId">
    <%= @game.kid.id %>
  </div>

  <%# Starting the game %>
  <div class="container">

    <h1><%= @game.name %></h1>

    <div class="my-5" data-action="click->game#playSound">
      <%# Audio of the exercise %>
      <% if female && @game.name == "Colors" %>
            <audio src="<%= audio_path 'A-Vermelho.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif @game.name == "Colors"  %>
            <audio src="<%= audio_path 'F-Vermelho.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif female && @game.name == "Animals" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif @game.name == "Animals" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif female && @game.name == "Fruits" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif @game.name == "Fruits" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif female && @game.name == "Rooms" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "exercise"></audio>
          <% elsif @game.name == "Rooms" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "exercise"></audio>
          <% end %>

      <div class="card audio-game">
        <h2><i class="fa-solid fa-volume-high" style="color: #ffffff;" data-action="click->game#playSound"></i></h2>
      </div>
    </div>

    <div class="d-flex justify-content-evenly my-3">

      <div class="card rounded-4" data-game-target="wrongAnswer1Card">
        <div data-action="click->game#playWrongAnswer1">
          <%# Audio of the first card %>
          <% if female && @game.name == "Colors" %>
            <audio src="<%= audio_path 'A-Azul.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif @game.name == "Colors"  %>
            <audio src="<%= audio_path 'F-Azul.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif female && @game.name == "Animals" %>
            <audio src="<%= audio_path 'A-Elefante.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif @game.name == "Animals" %>
            <audio src="<%= audio_path 'F-Elefante.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif female && @game.name == "Fruits" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif @game.name == "Fruits" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif female && @game.name == "Rooms" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% elsif @game.name == "Rooms" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "wrongAnswer1"></audio>
          <% end %>
          <%= cl_image_tag @game.photos[0].key, height: 130, width: 130, crop: :fill %>
        </div>
      </div>

      <div class="card rounded-4" data-game-target="wrongAnswer2Card">
        <div data-action="click->game#playWrongAnswer2">
          <%# Audio of the second card %>
          <% if female && @game.name == "Colors" %>
            <audio src="<%= audio_path 'A-Amarelo.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif @game.name == "Colors"  %>
            <audio src="<%= audio_path 'F-Amarelo.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif female && @game.name == "Animals" %>
            <audio src="<%= audio_path 'A-Girafa.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif @game.name == "Animals" %>
            <audio src="<%= audio_path 'F-Girafa.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif female && @game.name == "Fruits" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif @game.name == "Fruits" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif female && @game.name == "Rooms" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% elsif @game.name == "Rooms" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "wrongAnswer2"></audio>
          <% end %>
          <%= cl_image_tag @game.photos[1].key, height: 130, width: 130, crop: :fill %>
        </div>
      </div>

    </div>

    <div class="d-flex justify-content-evenly">

      <div class="card rounded-4" data-game-target="wrongAnswer3Card">
        <div data-action="click->game#playWrongAnswer3">
          <%# Audio for the third card %>
          <% if female && @game.name == "Colors" %>
            <audio src="<%= audio_path 'A-Verde.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif @game.name == "Colors"  %>
            <audio src="<%= audio_path 'F-Verde.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif female && @game.name == "Animals" %>
            <audio src="<%= audio_path 'A-Tigre.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif @game.name == "Animals" %>
            <audio src="<%= audio_path 'F-Tigre.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif female && @game.name == "Fruits" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif @game.name == "Fruits" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif female && @game.name == "Rooms" %>
            <audio src="<%= audio_path 'A-Leao.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% elsif @game.name == "Rooms" %>
            <audio src="<%= audio_path 'F-Leao.mp3'%>" data-game-target= "wrongAnswer3"></audio>
          <% end %>
          <%= cl_image_tag @game.photos[2].key, height: 130, width: 130, crop: :fill %>
        </div>
      </div>

      <div class="card rounded-4" data-confetti-follow-value="false" data-controller="confetti" data-action="click->confetti#spray" data-animation-value="basic">
        <div data-action="click->game#playWin">
          <%# Audio for the winner card %>
          <% if female && @game.name == "Colors" %>
            <audio src="<%= audio_path 'A-Vermelho-parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif @game.name == "Colors"  %>
            <audio src="<%= audio_path 'F-Vermelho-parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif female && @game.name == "Animals" %>
            <audio src="<%= audio_path 'A-Leao-Parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif @game.name == "Animals" %>
            <audio src="<%= audio_path 'F-Leao-parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif female && @game.name == "Fruits" %>
            <audio src="<%= audio_path 'A-Leao-Parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif @game.name == "Fruits" %>
            <audio src="<%= audio_path 'F-Leao-parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif female && @game.name == "Rooms" %>
            <audio src="<%= audio_path 'A-Leao-Parabens.mp3'%>" data-game-target= "win"></audio>
          <% elsif @game.name == "Rooms" %>
            <audio src="<%= audio_path 'F-Leao-parabens.mp3'%>" data-game-target= "win"></audio>
          <% end %>
          <%= cl_image_tag @game.photos[3].key, height: 130, width: 130, crop: :fill %>
        </div>
      </div>

    </div>
    <footer>
      <%= link_to lecture_kid_game_path(@game.kid, @game) do %>
        <h2 class="game-btn"><i class="fa-solid fa-left-long"></i></h2>
      <% end %>
    </footer>
  </div>
</div>

app/views/kids/edit.html.erb
<%= render "shared/sidebar", kid: @kid %>

<div class="container" data-controller="avatar">
   <div class="d-none" data-avatar-target="kidId">
    <%= @kid.id %>
  </div>

  <h1 class="text-center">
    Who do you want to be, <%= @kid.nickname.capitalize %>?
  </h1>
  <br>

    <div class="d-flex justify-content-around mt-1" >

      <div class="avatar-display" data-action="click->avatar#moanaAvatar">
        <audio src="<%= audio_path 'A-Moana.mp3'%>" data-avatar-target="moana"></audio>
        <%= cl_image_tag @moana.photo.key, class:"avatar shadow avatar-edit" %>
        <h5 class="avatar-edit text-center mt-3"><%= @moana.name.capitalize %></h5>
      </div>

      <div class="avatar-display" data-action="click->avatar#pocahontasAvatar">
        <audio src="<%= audio_path 'A-Pocahontas.mp3'%>" data-avatar-target="pocahontas"></audio>
        <%= cl_image_tag @pocahontas.photo.key, class:"avatar shadow avatar-edit" %>
        <h5 class="avatar-edit text-center mt-3"><%= @pocahontas.name.capitalize %></h5>
      </div>
    </div>

    <div class="d-flex justify-content-around my-4">
      <div class="avatar-display" data-action="click->avatar#mogliAvatar">
        <audio src="<%= audio_path 'Mogli.mp3'%>" data-avatar-target="mogli"></audio>
        <%= cl_image_tag @mogli.photo.key, class:"avatar shadow avatar-edit"  %>
        <h5 class="avatar-edit text-center mt-3"><%= @mogli.name.capitalize %></h5>
      </div>

      <div class="avatar-display" data-action="click->avatar#tarzanAvatar">
        <audio src="<%= audio_path 'Tarzan.mp3'%>" data-avatar-target="tarzan"></audio>
        <%= cl_image_tag @tarzan.photo.key, class:"avatar shadow avatar-edit"  %>
        <h5 class="avatar-edit text-center mt-3"><%= @tarzan.name.capitalize %></h5>
      </div>
    </div>

  <div class="d-flex justify-content-around mt-4 mb-2">
    <% if @kid.total_score >= 1 %>
      <div class="avatar-display" data-action="click->avatar#simbaAvatar">
        <audio src="<%= audio_path 'Simba.mp3'%>" data-avatar-target="simba"></audio>
        <%= cl_image_tag @simba.photo.key, class:"avatar shadow avatar-edit avatar-win"  %>
        <h5 class="avatar-edit text-center mt-3"><%= @simba.name.capitalize %></h5>
      </div>
    <% end %>

    <% if @kid.total_score >= 2 %>
        <div class="avatar-display" data-action="click->avatar#arielAvatar">
          <audio src="<%= audio_path 'A-Ariel.mp3'%>" data-avatar-target="ariel"></audio>
          <%= cl_image_tag @ariel.photo.key, class:"avatar shadow avatar-edit avatar-win"  %>
          <h5 class="avatar-edit text-center mt-3"><%= @ariel.name.capitalize %></h5>
        </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-around mt-4 mb-2">
    <% if @kid.total_score >= 3 %>
        <div class="avatar-display" data-action="click->avatar#capitaoAvatar">
          <audio src="<%= audio_path 'A-Ariel.mp3'%>" data-avatar-target="capitao"></audio>
          <%= cl_image_tag @capitao.photo.key, class:"avatar shadow avatar-edit avatar-win"  %>
          <h5 class="avatar-edit text-center mt-3"><%= @capitao.name.capitalize %></h5>
        </div>
    <% end %>

    <% if @kid.total_score >= 4 %>
        <div class="avatar-display" data-action="click->avatar#frozenAvatar">
          <audio src="<%= audio_path 'A-Ariel.mp3'%>" data-avatar-target="frozen"></audio>
          <%= cl_image_tag @frozen.photo.key, class:"avatar shadow avatar-edit avatar-win"  %>
          <h5 class="avatar-edit text-center mt-3"><%= @frozen.name.capitalize %></h5>
        </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-center">
    <%= link_to "LET'S PLAY", kid_games_path(@kid), class:"btn-brown" %>
  </div>
</div>

app/views/kids/index.html.erb
<%= render "shared/logo" %>

<div class="container kids-index">

<% if @kids.any? %>
  <div>
    <h1><strong>Who wants to play?</strong></h1>
  </div>
    <% @kids.each do |kid| %>
      <div class="kids-card mt-5">
        <%= link_to  kid_games_path(kid), class:"text-decoration-none" do %>
          <%= cl_image_tag kid.avatar.photo.key, class:"avatar shadow" %>
        <% end %>
          <h2 class="my-4"><strong><%= kid.nickname %></i></strong></h2>

          <%= link_to kid_path(kid), data: { turbo_method: :delete, turbo_confirm: "Are you sure you don't wanna play anymore?" }, class:"delete-btn" do %>
          <i class="fa-solid fa-trash-can trash-icon"> </i>
        <% end %>
      </div>
    <% end %>
    <% else %>
      <h1><strong>Where are the kids?</strong></h1>
      <h1>😃</h1>
      <br>
      <h4><em>You can add the first player by clicking here:</em></h4>
    <% end %>

  <footer>
    <%= link_to new_kid_path do%>
      <i class="fa-solid fa-circle-plus add-icon"></i>
    <% end %>
  </footer>
</div>

app/views/kids/new.html.erb
<%= render "shared/logo" %>

<div class="container">

<h1 class="text-center">New player</h1>

<div class="new-kid-form">
  <br>
      <%= simple_form_for @kid do |f| %>
      <%= f.input :nickname, :label => 'nickname' %>
      <%= f.input :age, as: :integer %>
      <div class="d-flex justify-content-center">
        <%= f.button :submit, "CHOOSE YOUR AVATAR", class:"btn-brown" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbo-cache-control" content="no-preview">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>

    <%= render "shared/flashes" %>
    <div class="bg-img" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_map-navbar.html.erb
<div class="d-flex justify-content-between map-bg" style="height:15vh;">

  <div id="mySidenav" class="sidenav rounded-end-4">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

    <%= cl_image_tag kid.avatar.photo.key, class:"image-sidebar" %>

    <p class="sidebar-nickname"><%= kid.nickname %></p>

    <hr class="pill">

    <h2 class="sidebar-text text-nowrap overflow-hidden"> LEVEL <br>
     <i class="fa-solid fa-bolt mt-3"></i> <%= kid.total_score + 1 %>
    </h2>

    <hr class="pill">

    <h2 class="mt-4">
      <%= link_to kid_path(kid), class:"sidebar-title" do %>
        <i class="fa-solid fa-house-user pb-2"></i>
        <h5> PROFILE </h5>
      <% end %>
    </h2>

    <h2>
      <%= link_to kid_games_path(kid), class:"sidebar-title" do %>
        <i class="fa-solid fa-map pb-2"></i>
        <h5> MAP</h5>
      <% end %>
    </h2>

    <h2>
      <%= link_to edit_kid_path(kid), class:"sidebar-title" do %>
        <i class="fa-solid fa-circle-user pb-2"></i>
        <h5> AVATAR </h5>
      <% end %>
    </h2>

    <hr class="pill">

    <h2>
      <%= link_to kids_path(kid), class:"sidebar-players" do %>
        <i class="fa-solid fa-user-plus pb-2"></i>
        <h5> PLAYERS </h5>
      <% end %>
    </h2>

    <hr class="pill">

  </div>

  <span onclick="openNav()"><%= cl_image_tag kid.avatar.photo.key, class:"image-avatar" %></span>


  <script>
  function openNav() {
    document.getElementById("mySidenav").style.width = "200px";
  }


  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
  }
  </script>

  <%= image_tag "ks-logo.png", class:"image-logo" %>

</div>

app/views/shared/_sidebar.html.erb
<div class="d-flex justify-content-between">

  <div id="mySidenav" class="sidenav rounded-end-4">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

    <%= cl_image_tag kid.avatar.photo.key, class:"image-sidebar" %>

    <p class="sidebar-nickname"><%= kid.nickname %></p>

    <hr class="pill">

    <h2 class="sidebar-text text-nowrap overflow-hidden"> LEVEL <br>
     <i class="fa-solid fa-bolt mt-3"></i> <%= kid.total_score + 1 %>
    </h2>

    <hr class="pill">

    <h2 class="mt-4">
      <%= link_to kid_path(kid), class:"sidebar-title" do %>
        <i class="fa-solid fa-house-user pb-2"></i>
        <h5> PROFILE </h5>
      <% end %>
    </h2>

    <h2>
      <%= link_to kid_games_path(kid), class:"sidebar-title" do %>
        <i class="fa-solid fa-map pb-2"></i>
        <h5> MAP</h5>
      <% end %>
    </h2>

    <h2>
      <%= link_to edit_kid_path(kid), class:"sidebar-title" do %>
        <i class="fa-solid fa-circle-user pb-2"></i>
        <h5> AVATAR </h5>
      <% end %>
    </h2>

    <hr class="pill">

    <h2>
      <%= link_to kids_path(kid), class:"sidebar-players" do %>
        <i class="fa-solid fa-user-plus pb-2"></i>
        <h5> PLAYERS </h5>
      <% end %>
    </h2>

    <hr class="pill">

  </div>

  <span onclick="openNav()"><%= cl_image_tag kid.avatar.photo.key, class:"image-avatar" %></span>


  <script>
  function openNav() {
    document.getElementById("mySidenav").style.width = "200px";
  }


  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
  }
  </script>

  <%= image_tag "ks-logo.png", class:"image-logo" %>

</div>